Campaign stuff
TheTh1rt33nth/Nexus-octo-engine pull request #3
Opened 2021-03-31 07:33 UTC by TheTh1rt33nth

Pls fix easyjson(((

2021-04-02 08:25 UTC, f0m41h4u7 commented on internal/app/CampaignManagement.go
> +  if lore!=nil{
hmmm i thought string doesn't have nil value...

2021-04-02 08:26 UTC, f0m41h4u7 commented on internal/app/rostermanagement.go
> +func RPonSL (armyID int){
wow so understandable )

2021-04-02 08:35 UTC, f0m41h4u7 commented on internal/app/CampaignManagement.go
> +  if lore!=nil{
yes, it actually doesn't

2021-04-02 08:45 UTC, TheTh1rt33nth commented on internal/app/rostermanagement.go
> +func RPonSL (armyID int){
Spending requisition points on supply limit))

2021-04-02 08:46 UTC, f0m41h4u7 commented on internal/app/rostermanagement.go
> +func RPonSL (armyID int){
во имя Омниссии это же так obvious очевидно понятно ваще жесть !

2021-04-02 08:47 UTC, f0m41h4u7 requested changes
rename the function pleas !!
or at least write a comment above it

2021-04-03 13:43 UTC, f0m41h4u7 commented on internal/app/roster_management.go
> +func CPbyPL(pl int) int {
eto chto

2021-04-03 13:44 UTC, f0m41h4u7 commented on internal/app/roster_management.go
> +func CPbyPL(pl int) int {
```suggestion
func PLtoCP(pl int) int {
```

2021-04-03 13:44 UTC, f0m41h4u7 approved these changes

2021-04-03 13:45 UTC, f0m41h4u7 commented on internal/app/roster_management.go
> +	cp += CPbyPL(pl)
```suggestion
	cp += PLtoCP(pl)
```

2021-04-03 13:47 UTC, merged